wooga/atlas-build-unity

build.gradle
src/integrationTest/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/KeychainLookupList.groovy
src/main/groovy/wooga/gradle/build/unity/ios/internal/utils/SecurityUtil.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/KeychainTask.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ListKeychainTask.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/XCodeExportTask.groovy
src/test/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginActivationSpec.groovy
src/test/groovy/wooga/gradle/build/unity/ios/KeychainLookupListSpec.groovy

The custom build keychain was only removed from the keychain lockup list when the build succeeded. This patch changes the internal task setup to ensure that the task `:removeKeychain` runs always when executing the whole pipeline (`:assemble`)
[REMOVE]:http://resources.atlas.wooga.com/icons/icon_remove.svg …

Fix remove build keychain after build

---

src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfile.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/KeychainTask.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ListKeychainTask.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/LockKeychainTask.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/XCodeArchiveTask.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/XCodeExportTask.groovy

Update the structure of the `build` directory after a gradle run.
```
build
├── archives
│  └── GradleUnityBuildTest-0.4.0.xcarchive
├── derivedData
│  └── ...
├── ipas
│  └── GradleUnityBuildTest-0.4.0.ipa
├── outputs
│  ├── GradleUnityBuildTest-0.4.0-dSYM.zip
│  └── GradleUnityBuildTest-0.4.0.ipa
├── sign
│  └── keychains
├── symbols
│  └── GradleUnityBuildTest-0.4.0-dSYM.zip
└── tmp
└── ...
```
* archives contains all compiled `xcarchives` (not getting cleaned)
* ipas contains all exported `ipa` packages (not getting cleaned)
* symbols contains all zipped DSYM files (not getting cleaned)
* outputs contains the `ipa` and symbols of the last successful build
* ![IMPROVE]![IOS] `build` directory structure
* ![FIX] multiple `ipa` packages in `outputs` directory
resolves #4 …

Refactor iOS task input outputs

---

src/integrationTest/groovy/wooga/gradle/build/unity/tasks/GradleBuildIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/GradleBuild.groovy

If you choose to build the whole unity project with `--info` loglevel than this log setting isn't passed down to the exported sub-projects. This patch adds this functionality by reading the log level from the
`StartParameter` object and setting the matching commandline switches. 
The only supported levels are:
* debug
* info
* quiet …

Pass loglevel from main gradle project to the sub projects

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/KeychainTaskSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfile.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/KeychainTask.groovy

The `up-to-date` check for the `:buildKeychain` task always returned `false` because gradle believed the output file wasn't generated by gradle. I made a simple mistake in the `OutputFiles` definition for the task. I used a `FileTree` to create the `FileCollection` which yields a size `0` list when building a clean build. Next build would delete the output file because gradle never recorded it as a output file. So this pattern happens over and over again with each rebuild.
I switched from `project.fileTree` to `project.files` and pass in a `File` object. I can't remember why I used the fileTree in the first place. I also changed that for `:importProvisioningProfiles`. I added a testspec for the keychain task but not yet for the provisioning profiles one because of `fastlane`. …

Fix up-to-date check for task :buildKeychain

---

src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTask.groovy

During task execution of `UnityBuildPlayerTask` aka `export${Platform}${Environment}`, the version passed to unity was fetched from the project. If the project version changes the task has no tracking information of the old value so it things the task is still `up-to-date`.
This patch adds a new `Input` property called `version` to the `UnityBuildPlayerTask` class and maps the default value to `project.version`. …

Fix up-to-date check for export task when project version changes

---

Jenkinsfile
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTask.groovy

The task had only a getter for the inputFiles property. This getter returned a `FileTree` containing only files within `Assets` directory. This patch moves the default definition into a convention map closure in `UnityBuildPlugin`. The `inputFiles` is also now annotated with `SkipWhenEmpty`. Convention mapping sets a wider `FileCollection` containing files from `Assets`, `ProjectSettings` and `UnityPackageManager` directory. The `Assets` directory tree is still filtered. So plugin sources from different build platforms don't trigger an input file changed. I also added `Editor` folders to this filter.
See `UnityBuildPlayerTaskIntegrationSpec` for test cases. …

Fix UnityBuildPlugin inputFiles handling

---

src/integrationTest/groovy/wooga/gradle/build/unity/tasks/GradleBuildIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/GradleBuild.groovy

Some properties had no full test spec setup. So I added some more test cases for `buildArguments` and `tasks` properties. While add it I added more standart API variants and added tests as well.
I also found an issue with the passed down log levels. If the `buildArguments` would contain a log level switch like `--info` it would be overriden. So I added some tests for this case and check if `buildArguments` already contain a log switch flag.
Also changed the output stream for `stderr` to `stderr` …

Improve GradleBuild task interface and specs

---

src/integrationTest/groovy/wooga/gradle/build/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/internal/utils/PropertyUtils.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTask.groovy

Description
===========
The `project.version` property is by default an `Object`. In most cases it will be a `String` value. I changed the way we set this `version` value from a direct assignment into a convention mapping (#9). What is important to note is that instead of the original `getter` the mapped `closure` will be executed instead. I added a lot of conversion methods to convert an object into a `String`. This wasn't done in the mapping. 
I added a very quick regression test in `UnityBuildPluginIntegrationSpec`. I wanted to do the same for the iOS plugin but this is impossible at the moment due to the untestable state of the plugin. I also moved some test/utility methods around to test/execute the logic without major code duplications
Changes
======= …

Fix version to string conversion crash

---

README.md
gradle/wrapper/gradle-wrapper.properties
gradle_check_versions.sh
src/integrationTest/groovy/wooga/gradle/build/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/GradleBuildIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/internal/DefaultIOSBuildPluginExtension.groovy

This patch updates the used gradle version for development to `4.10`. This concludes the support of the gradle `4.x` version range as `4.10` is the last version before `5.0`
see wooga/rfcs#2
* Gradle >= `4.8` changed the output stream for errors
* Gradle 4.10 moved the internal class `DefaultPasswordCredentials`
* Gradle 4.10 changed internal `FileTreeElement` behavior
[ADD]:http://atlas-resources.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:http://atlas-resources.wooga.com/icons/icon_improve.svg "Improve"
[CHANGE]:http://atlas-resources.wooga.com/icons/icon_change.svg "Change"
[FIX]:http://atlas-resources.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:http://atlas-resources.wooga.com/icons/icon_update.svg "Update" …

Update gradle support version to 4.10

---

src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/internal/DefaultUnityBuildPluginExtension.groovy

This patch adds a new property `ignoreFilesForExportUpToDateCheck` to the `UnityBuildPluginExtension` extension. The files in this `ConfigurableFileCollection` will excluded from the default `inputFiles` collection for `UnityBuildPlayerTask`.
[REMOVE]:http://resources.atlas.wooga.com/icons/icon_remove.svg …

Add ignoreFilesForExportUpToDateCheck property to exclude files for up-to-date check

---

src/integrationTest/groovy/wooga/gradle/build/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy

This patch fixes some minor issues with the integration test setup. We need to disable the gradle 5 compatibility warnings as all tests fail because of it. There is also a setup bug for the provided build targets in the mock app configs. We should only test with valid build target values. …

Fix integration test build setup

---

src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/GradleBuildIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/GradleBuild.groovy

For newer Unity version it is desired that the exported gradle project runs with a configured gradle version. At the moment, gradle uses the same version as the root project version to execute the build in the exported projects. This patch allows to set a custom gradle version in the `appConfig`. Gradle will fall back to the root gradle version if the property `gradleVersion` is not defined.
[UPDATE]:http://resources.atlas.wooga.com/icons/icon_update.svg …

Improve inner task execution by providing gradle version to execute with

---

build.gradle
src/integrationTest/groovy/wooga/gradle/build/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfileSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfile.groovy

The `ImportProvisioningProfile` task should never be `up-to-date`. A provisioning profile can change remotely without warning. Input caching can make this task to be marked `up-to-date`. This patch sets the output `upToDateWhen` spec to be always false. It would be possible to write a custom timeout handler but this is to much effort for a task that runs maximum of 15 seconds
I had to adjust the source slightly to be able to test this new task caching behavior. I added a custom static getter `getExecutable` to the `ImportProvisioningProfile` class. This helper methods tries to find the path to the given executable in the environment `PATH`. The reason for this change is that I need a way to inject a mock `fastlane` executable. I can't override the path of the spawned gradle job so opted …

Disable caching for ImportProvisioningProfile task

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfileSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/ios/internal/DefaultIOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfile.groovy

Fastlane `sigh` tries to find a matching provisioning profile based on the `team_id` and `app_id` parameters. There could be multiple valid profiles matching these criteria and fastlane will by default download the first one it find. There is an option to download all matching profiles but I opted to not support this switch for now because this would mean the task has to generate multiple output files as well which would be a bigger change. There is another filter switch `--provisioning_name`. With this switch set, `sigh` tries to find a matching profile with exactly that name.
The last patch added basic test setup for the `ImportProvisioningProfile` task class. This patch doubles down on it and provides a matrix test for all task input properties. It only checks the invocation of …

Add provisioningName property to ImportProvisioningProfile

---

src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginConsts.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/internal/DefaultUnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTask.groovy

A long with the `toolsVersion` and gradle project version we want to know the current `commitHash` in Unity without quering git. This patch adds a new property `commitHash` to the
`UnityBuildPlayerTask` class. The property is configured similar as the `toolsVersion` property. There is a fallback to the `UNITY_BUILD_COMMIT_HASH` environment variable and `unityBuild.commitHash` gradle property
resolves: #43 
* ![ADD] 'commitHash' property to `UnityBuildPlayerTask` …

Add 'commitHash' property to UnityBuildPlayerTask

---

src/integrationTest/groovy/wooga/gradle/build/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfileSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/ios/internal/DefaultIOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfile.groovy

To import _adhoc_ provisioning profiles with `fastlane` correctly in case of _adhoc_ builds we need to tell fastlane that we want an _adhoc_ profile. Fastlane will fail and try to generate a _store_ or _enterprise_ profile instead.
This patch adds a new property `adhoc` to `ImportProvisioningProfile` and `IOSBuildPluginExtension` which will pass this information over to fastlane. It would had been possible to set `SIGH_AD_HOC` to make this clearer in both useage and output.
Because of the nature of boolean values (true/false there is no notion of not set) this new logic will always set the `--adhoc` field. When we swich to the gradle provider API this issue will be fixed since a gradle property has the information of `present` or not. This also means that the environment variable …

Add iOS adhoc support

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/KeychainTaskSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/KeychainTask.groovy

The `buildKeychain` task for iOS projects uses the `security` commandline tool to setup a new keychain and import optional certificates. This operation is handled in the _interactive_ mode to
spawn only one `security` process. In case of an error we only show a message that `security` failed but not exactly what failed. I changed the task to register both `stderr` and `stdout` and print both to the gradle logger. In additon to this I also handle the exit value and throw a `ExecException` with the `stderr` string as message. This should result in a clearer error message. 
As an example. If the user provides a wrong certificate (.p12) passphrase the gradle process would end like:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildKeychain'.
> …
```

Improve iOS keychain task error messages

---

docs/api/index-all.html
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/GradleBuildIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginConsts.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/internal/DefaultUnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/GradleBuild.groovy
src/main/resources/buildUnityExportInit.gradle
src/main/resources/exportMarker.gradle

Exporting and building an exported gradle project from unity will at the moment move the `build` directory of all projects of the exported project to a custom location. As an example:
_a project exported to `build/export/ios/project`_ will have its gradle cache dir and build dir set to `build/export/ios/buildCache`.
This was achieved by loading a gradle init script from the current project directory named `exportInit.gradle`. This script needed the following content and was *not* part of this plugin:
```groovy
println "------------------------------------------------------------"
println "                        INIT                                "
println "------------------------------------------------------------"
projectsLoaded {
def buildDirBase = …
```

Refactor external build cache setup and configuration

---

src/main/groovy/wooga/gradle/build/unity/ios/internal/DefaultIOSBuildPluginExtension.groovy
src/test/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginSpec.groovy

The `Boolean` type initializes with the value `null` instead of `false`. This patch simply sets a default value to `false`. I also added missing tests to verify it.
* ![FIX] ![IOS] `adhoc` property default value in extension …

Fix adhoc property default value in extension

---

build.gradle

Due to a security issue with the old versions of the `com.gradle.plugin-publish` plugin,
all version < 0.11.0 won't function anymore. We needed to update to the latest version
to be able to publish plugins.
* ![UPDATE] `net.wooga.plugins` to `0.5.0`
[REMOVE]:http://resources.atlas.wooga.com/icons/icon_remove.svg …

Update net.wooga.plugins to 0.5.0

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/FastlaneSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfileSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/PublishTestFlightSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/ios/internal/DefaultIOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/PublishTestFlight.groovy
src/test/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginSpec.groovy

This patch adds a new task type `PublishTestFlight` to the plugin. This task uses `fastlane pilot upload`. This solution would bring the most options for the future but I'm still unsure if we should not simple use `altool`. The plugin creates a new task `publishTestFlight` and hooks are the base information like fastlane credentials and path to the `ipa` being published.
The publish task nows a few more parameters that are passed down to `fastlane pilot upload`
| parameter | fastlane flag | description |
| --------- | ------------- | ----------- |
| appIdentifier | --app_identifier | STRING The bundle identifier of the app to upload or manage testers
| teamId | --team_id | The ID of your App Store Connect team if you're in multiple teams
| teamName | --team_name | STRING The name of your …

Add testflight publish

---

src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/XCodeArchiveTask.groovy

During archive and the resulting code sign, it can happen that Xcode has issues with ambigious certificate names. It is possible to provide a `DEVELOPMENT_TEAM` flag during invocation and providing the teamId for code sign.
This patch adds a new optional task input variable `teamId` to the `Archive` task and sets the `DEVELOPMENT_TEAM` option during execution if the property is set. The plugin will provide a default value from the plugin extension.
Changes
=======
* ![IMPROVE] ![IOS] `ArchiveTask` provide optional team id
[CHANGE]:http://resources.atlas.wooga.com/icons/icon_change.svg …

Improve iOS ArchiveTask provide optional team id

---

src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginConsts.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/internal/DefaultUnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTask.groovy

This patch adds main support for a second version specifier the `versionCode`. The `versionCode` is a `String` property even though android uses an integer.
1. To pass it down to unity it has to be converted to `String` anyways
2. iOS has different rules for the [`CFBundleVersion`] which is a `String`
The default value is `null` and won't be send to Unity. The property can be set on the `UnityBuildPlayerTask` or in the `buildUnity` extension. In the later case all tasks of type `UnityBuildPlayerTask` will have the same value set. It is also possible to set the value via environmen or gradle properties. I also made the `version` property of the extension overrideable via environment or gradle properties. The main fallback is still the project version. Only if this value for project.version …

Add versionCode property

---

src/main/groovy/wooga/gradle/build/unity/secrets/EncryptedSecret.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/Secret.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/SecretResolver.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/SecretResolverException.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/AbstractEncryptedSecret.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/DefaultResolver.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/DefaultSecret.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/EncryptedSecretFile.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/EncryptedSecretText.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/Resolver.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/SecretFile.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/SecretText.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/Secrets.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/EncryptedSecretFileSpec.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/EncryptedSecretSpec.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/EncryptedSecretTextSpec.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/EncryptionSpecHelper.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/SecretSpec.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/SecretsSpec.groovy

see wooga/wdk-unity-UnifiedBuildSystem#94
This patch brings in base type for future secret handling. These types are planned as a base API for further detailed implementation in future patches / plugin extensions.
We have three basic sets of types
* _secrets_ - a wrapper type that holds a secret value
* _resolver_ - a basic object that can resolve a secret
* _secrets_ a map like structure to hold secrets in memory
The exposed type is an interface with a pretty simple API
```groovy
interface Secret<T> {
T getSecretValue()
}
```
There is one base implementation available (`DefaultSecret`) and two concrete implementations for secret file (`byte[]`) and secret text (`String`). The concrete classes are only added for completion and are used in some unit tests.
A second extended form of secret …

Add secret handling base types

---

src/integrationTest/groovy/wooga/gradle/build/UnityIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/UnityBuildPluginSecretHandlingIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/FetchSecretsTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/GradleBuildIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/SecretSpecIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/SecretSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginConsts.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/internal/DefaultUnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/internal/MemoisationProvider.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/FetchSecrets.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/GradleBuild.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTask.groovy
src/test/groovy/wooga/gradle/build/unity/internal/MemoisationProviderSpec.groovy

depends on #59 
see wooga/wdk-unity-UnifiedBuildSystem#94
This is a pretty huge patch and implements the basic tools needed to fetch and pass secrets to Unity. The patch [#105] is introducing a new configuration field called `secrets` to the `AppConfig`. The fields intention is to declare all secretIds needed byt the `AppConfig`. This patch implements the basic workflow to read the secretsIds, fetch the secrets through a `SecretResolver` and pass them to Unity via environment variables (this is the plan for the first implementation).
I added a new task type `FetchSecrets` and configured tasks for all found `AppConfig` files in the `AppConfig` lookup directory. This means every `UnityBuildPlayerTask` generated from the plugin will have a corresponding `FetchSecrets` task as a direct …

Add secrets resolver base setup

---

Jenkinsfile
build.gradle
src/main/groovy/wooga/gradle/build/unity/secrets/BasicAWSCredentials.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/AWSSecretsManagerResolver.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/EnvironmentResolver.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/SecretResolverChain.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/AWSSecretsManagerResolverSpec.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/EnvironmentResolverSpec.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/SecretResolverChainSpec.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/SecretsResolverSpec.groovy

dependson #58 
This patch provides 3 implementation types for `SecretResolver`.
* `EnvironmentResolver` -> resolve secrets from the current process environment
* `AWSSecretsManagerResolver` -> resolve secrets from AWS
* `SecretResolverChain` -> Chain many resolvers together
Only two of the provided implementations are actually capeable to fetch secret values. The `SecretResolverChain`'s main purpose is to provide a way to declare multiple resolver in a fallback chain setup.
* ![ADD] `EnvironmentResolver` class
* ![ADD] `AWSSecretsManagerResolver` class
* ![ADD] `SecretsResolverChain` class
[IMPROVE]:http://resources.atlas.wooga.com/icons/icon_improve.svg …

Add secret resolver implementations

---

src/integrationTest/groovy/wooga/gradle/build/unity/UnityBuildPluginSecretHandlingIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/FetchSecretsTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/SecretSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginConsts.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/internal/DefaultUnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/FetchSecrets.groovy

To keep the connection between this plugin and the internal library as loose as possible I changed the appConfig lookup key to be configurable. The default value is the new key used by the library `secretIds`. The key can be changed to any string value in the task or for all fetchSecret task via the plugin extension
* ![CHANGE] make appConfig secret ids lookup key configurable …

Allow appConfig lookup key to be configurable

---

src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/PodInstallTask.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/XCodeArchiveTask.groovy
src/main/groovy/wooga/gradle/build/unity/secrets/internal/AWSSecretsManagerResolver.groovy
src/test/groovy/wooga/gradle/build/unity/secrets/internal/AWSSecretsManagerResolverSpec.groovy

This patch adds a new task `podInstall` to the plugin which is a dependend task for `xcodeArchive`. It only executes when a `Podfile` is in the project directory. The `xcodeArchive` task has a new workspace property which is set by default to the workspace generated by podInstall. The workspace has a higher precedance than the project. If the workspace does not exist the task falls back to the project.
The issue is the very nature how cocoapods handles workspaces. You can configure pods to use a preexisting workspace or it generates a new workspace based on the project it finds in the same directory.
The current patch only tries to solve a current workflow issue and needs changes and tests!
* ![ADD] `pods` and `workspace` support
[NEW]:https://atlas-resources.wooga.com/icons/icon_new.svg …

Add pods and workspace support

---

src/integrationTest/groovy/wooga/gradle/build/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/FetchSecretsTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/internal/DefaultUnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/FetchSecrets.groovy

This patch is a preparation to split the secrets handling code from this plugin. The `FetchSecrets` task has a property `appConfigFile` which contains a list of `secretIds` to fetch. To make the task more generic I removed these properties and replaced it with a new property: `final ListProperty<String> secretIds` and provided the implementation details where these secretsIds are coming from in the `UnityBuildPlugin` class. This allows me to split out this task into it's own plugin without ties to UBS.
* ![CHANGE] `FetchSecrets` task AppConfig dependency …

Change FetchSecrets dependency to AppConfig

---

src/integrationTest/groovy/wooga/gradle/build/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/internal/DefaultUnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTask.groovy

The `UnityBuildPlayerTask` provides special UBS arguments with a special commandline flag `-CustomArgs` and a single long value with multiple arguments enoded as "key=value;". There was no dynamic way of addingvalues to this flag. This patch adds a new property `customArguments` to both `UnityBuildPlayerTask` and the `unityBuild` extension. The type of this property is a simple `Map`. Values provided in the extension will be configured for all export tasks unless they override this property.
```groovy
unityBuild {
customArguments = ["value1" : "some value", "aFile": new File("/some/file")]
}
```
```groovy
gradle.taskGraph.whenReady {
tasks.withType(wooga.gradle.build.unity.tasks.UnityBuildPlayerTask) { t ->
if(t.buildPlatform == "android") {
t.customArguments = ['foo':'bar']
}
}
}
``` …

Add support for custom arguments for the build player task

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/CocoaPodSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/PodInstallTaskSpec.groovy
src/main/groovy/wooga/gradle/build/unity/internal/ExecUtil.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ImportProvisioningProfile.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/PodInstallTask.groovy

Cocoapods is not autoupdating the specs repo on its own when calling pod install. This patch makes sure to call `pod repo update` before each `pod install` call.
This patch brings additional tests as well because the patch that added the pod install task did not provide any.
* ![IMPROVE] execute `pod repo update` before `pod install` …

Execute 'pod repo update' before install call

---

Jenkinsfile
src/integrationTest/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/KeychainTaskSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/KeychainLookupList.groovy
src/main/groovy/wooga/gradle/build/unity/ios/internal/utils/SecurityUtil.groovy
src/test/groovy/wooga/gradle/build/unity/ios/KeychainLookupListSpec.groovy

The `KeychainLookupList` first added to this project missused an undocumented feature in macOS to implement all keychain additions and removals without the need to execute the `security` commandline tool. The logic worked by altering the config plist for the security tool: `com.apple.security.plist`. This worked great and allowed to run the tests on a mocked config file without altering the state of the executing machine.
Since macOS 10.15 this solution became more and more brittle as this file was no longer created by default and is sometimes deleted. Multiple issues came up over the last few month so I decided to move the logic back to the `security` cli tool.
There is a huge drawback when it comes to tests. We would like to test the logic in isolation but there is only one global …

Improve internal keychain handling

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ListKeychainTask.groovy
src/test/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginSpec.groovy

This patch adds a new action `reset` to the `ListKeychainTask`. This action is conditional and bount to the environment variable `ATLAS_BUILD_UNITY_IOS_RESET_KEYCHAINS`. The variable is checked directly in the task implementation for now. The plugin configures a new task called `resetKeychains` and adds it as a dependency to the `addKeychain` task.
This change should help with _ghost keychains_ on the CI system.
* ![ADD] conditional reset of keychains …

Add conditional reset of the keychains before adding build keychain

---

src/integrationTest/groovy/wooga/gradle/xcodebuild/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/XcodeBuildIntegrationSpec.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPlugin.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginConsts.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/DefaultXcodeBuildPluginExtension.groovy
src/main/resources/META-INF/gradle-plugins/net.wooga.xcodebuild.properties
src/test/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginActivationSpec.groovy
src/test/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginSpec.groovy

This patch adds the base skeleton for the new `net.wooga.xcodebuild` plugin. The functionality with the first task will come in multiple patches
* ![ADD] `net.wooga.xcodebuild` plugin setup …

Add xcodebuild plugin setup

---

build.gradle
src/integrationTest/groovy/wooga/gradle/xcodebuild/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/XcodeBuildIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/XcodeArchiveIntegrationSpec.groovy
src/main/groovy/wooga/gradle/xcodebuild/ConsoleSettings.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeAction.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeActionSpec.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPlugin.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginConsts.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/DefaultXcodeBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/ForkTextStream.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/PropertyLookup.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/XcodeBuildAction.groovy
src/main/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeTask.groovy
src/test/groovy/wooga/gradle/xcodebuild/ConsoleSettingsSpec.groovy
src/test/groovy/wooga/gradle/xcodebuild/internal/ForkTextStreamSpec.groovy

This patch builds on top of the last addition and prepares a foundation for future tasks with some common settings for logging and console printing.
The console settings config object controls the logoutput of `xcodebuild` to the standart output. The tool is by nature very verbose and does't allow any verbosity levels to be set except to quiten it completely. In the apple  development szene is a tool available to help out with that [xcpretty]. It's main use is to transform the output of `xcodebuild` and format it in a shorter more human readable format. It also has formatters to reformat unit test output into different formats. The tool is written in ruby which doesn't help us much so I ported it over to groovy [xcpretty.groovy]. It is not a 100% port as code snippet colering is missing …

Add file and pretty console logging

---

src/main/groovy/wooga/gradle/xcodebuild/internal/ForkTextStream.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/LineBufferingOutputStream.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/TextStream.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/XcodeBuildAction.groovy
src/test/groovy/wooga/gradle/xcodebuild/internal/LineBufferingOutputStreamSpec.groovy

This is a tempoary fix. The whole outputhandling for xcpretty and logfile needs to be readressed. I copied the first solution from a different codebase which used the `LineBufferingOutputStream` from gradle without need that lines are only written when complete.
Ok the problem at hand that this patch will fix. I need an `OutputStream` implementation that waits for whole lines to be written before passing that down to another instance. I used a class from withing gradle without checking the implementatin details. The problem with this class is, that it writes out to the connected handler on the call `flush`. This method can and will be also called from the outside which can lead to chopped of lines.
I created now my own version of `LineBufferingOutputStream` to solve this little usability …

Fix line buffering output for logfile handling

---

src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeArchiveTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/ExportArchiveIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/XcodeArchiveIntegrationSpec.groovy
src/integrationTest/resources/xcodeProject/xcodebuildPluginTest.xcodeproj/project.pbxproj
src/main/groovy/wooga/gradle/xcodebuild/XcodeArchiveActionSpec.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeArchiveActionSpecBase.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPlugin.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeExportActionSpec.groovy
src/main/groovy/wooga/gradle/xcodebuild/config/BuildSettings.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/ForkTextStream.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/LineBufferingOutputStream.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/TextStream.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/XcodeBuildAction.groovy
src/main/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeArchiveTask.groovy
src/main/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeTask.groovy
src/main/groovy/wooga/gradle/xcodebuild/tasks/ExportArchive.groovy
src/main/groovy/wooga/gradle/xcodebuild/tasks/XcodeArchive.groovy
src/test/groovy/wooga/gradle/xcodebuild/internal/LineBufferingOutputStreamSpec.groovy

This patch adds the second most important xcodebuild functionality, the ability to create an `ipa` file from an exported `xcarchive`. The task is based on the new added abstract type `AbstractXcodeArchiveTask`. This new type shares the majority of properties with `XcodeArchive` and `ExportArchive`. I also changed the test setup to reflect this.
Exporting an unsigned ipa is not possible with `xcodebuild` because that is exactly what the command is for. Create a signed `ipa` package to upload apple or use to install a local version.
I added tests to verify the creation of an `ipa` file but guarded this with an `@Requires({ env.TEST_TEAM_ID })` statement. `TEST_TEAM_ID` should refer to a valid team for which both signing certificate and provisioning profile for appID …

Add ExportArchive task

---

src/integrationTest/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/ArchiveDebugSymbolsIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/ExportArchiveIntegrationSpec.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPlugin.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginConsts.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/DefaultXcodeBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/xcodebuild/tasks/ArchiveDebugSymbols.groovy
src/main/groovy/wooga/gradle/xcodebuild/tasks/XcodeArchive.groovy
src/test/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginSpec.groovy

The `ArchiveDebugSymbols` task is just a Zip task with no additonal overloads. I need to have a unique type name for the dynamic configuration. The task simply zips the `dSYM` directory inside a given `.xcarchive` as a preparation for deplyment to a symbolication/error analytics service.
I also add some new configuration that both an `ExportArchive` as well as an `ArchiveDebugSymbols` task is generated when a task of type `XcodeArchive` is added.
The generated tasks will take the `XcodeArchive` task name and append either `ArchiveDSYMS` or `Export`. A later patch will add the configuration to add these task outputs as project artifacts. So in theory never should actually call these tasks from the outside.
I adjusted some tests to take the effect of these autogenerated tasks as a given. I …

Add ArchiveDebugSymbols task type

---

src/integrationTest/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeArchiveTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/ArchiveDebugSymbolsIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/ExportArchiveIntegrationSpec.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeArchiveActionSpecBase.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPlugin.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/LineBufferingOutputStream.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/PropertyLookup.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/TextStream.groovy
src/main/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeArchiveTask.groovy

This patch adds the outputs for both `ExportArchive` and `ArchiveDebugSymbols` as publish artifacts to the `archives` configuration.
* ![ADD] publish artifact declaration
* ![ADD] missing copyright headers …

Add publish artifact declarations

---

build.gradle
src/main/groovy/wooga/gradle/xcodebuild/config/ExportOptions.groovy
src/test/groovy/wooga/gradle/xcodebuild/config/ExportOptionsSpec.groovy

This patch adds a helper model to work with the export options plist file needed for `xcodebuild --exportArchive`. This change only adds the model and tests. A further patch will use this implementation to read/create the plist file at buildtime.
* ![ADD] `ExportOptions` class …

Add ExportOptions class

---

src/integrationTest/groovy/wooga/gradle/fastlane/FastlaneSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/AbstractFastlaneTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/SighRenewIntegrationSpec.groovy
src/main/groovy/wooga/gradle/fastlane/FastlaneActionSpec.groovy
src/main/groovy/wooga/gradle/fastlane/internal/FastlaneAction.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/AbstractFastlaneTask.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/SighRenew.groovy

This patch adds a new task type `SighRenew` which will replace `ImportProvisioningProfile` in the `net.wooga.build-unity-ios` plugin. I created the same setup as for the new xcodebuild tasks. I did not create a new gradle plugin setup for the fastlane tasks as I don't know yet if it actually makes sense or not. The task is not yet fully integration tested since it is pretty much impossible to create and maintain the testsetup on the apple developer portal in order to test all functionalities.
* ![ADD] `SighRenew` task
[CHANGE]:http://resources.atlas.wooga.com/icons/icon_change.svg …

Add new SighRenew task

---

src/integrationTest/groovy/wooga/gradle/build/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/SecurityCreateKeychainIntegrationSpec.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/PilotUpload.groovy
src/main/groovy/wooga/gradle/macOS/security/InteractiveSecurityActionSpec.groovy
src/main/groovy/wooga/gradle/macOS/security/internal/InteractiveSecurityAction.groovy
src/main/groovy/wooga/gradle/macOS/security/internal/SecurityKeychainSettingsSpec.groovy
src/main/groovy/wooga/gradle/macOS/security/internal/SecurityKeychainSpec.groovy
src/main/groovy/wooga/gradle/macOS/security/tasks/AbstractInteractiveSecurityTask.groovy
src/main/groovy/wooga/gradle/macOS/security/tasks/SecurityCreateKeychain.groovy

As with the other lasts patches this one adds a new refactored taskimplementation for an older task. The new task `SecurityCreateKeychainIntegration` will partly replace `KeychainTask` from the `net.wooga.build-unity-ios`. I decided to split this task and create a separate task to import certificates. I'm still unsure if I should do the same for the keychain settings logic.
I tried something new with this patch. I moved some boilerplate propertie definitions into groovy trait objects. This allows me to reuse the same properties in multiple task classes without using inheritance.
*![ADD] ![MACOS] security task `SecurityCreateKeychainIntegration`
[NEW]:      https://resources.atlas.wooga.com/icons/icon_new.svg "New"
[ADD]:      https://resources.atlas.wooga.com/icons/icon_add.svg "Add" …

Add new macOS security task to create build keychain

---

src/integrationTest/groovy/wooga/gradle/fastlane/tasks/PilotUploadIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/SighRenewIntegrationSpec.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/PilotUpload.groovy

This is the second patch which will soon replace the old `fastlane` based task from `net.wooga.build-unity-ios`. The new task type `PilotUpdate` will soon replace the old `PublishTestFlight` implementation. This new task has nearly the same interface. It uses like all oter new types the Provider API to get rid of convention mapping as much as possible. The implementation uses a lot of the underlying abstract base class `AbstractFastlaneTask` which was introduced in the last patch (#86). This makes this change rather small. It supports logfile creation and the ability to add additional arguments in case fastlane adds more commandline arguments or we need to use a few of the ones I did not yet implement because of a good reason to have them in.
* ![ADD] `PilotUpload` task type …

Add PilotUpload task

---

src/integrationTest/groovy/wooga/gradle/fastlane/FastlaneIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/FastlanePluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/AbstractFastlaneTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/PilotUploadIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/SighRenewIntegrationSpec.groovy
src/main/groovy/wooga/gradle/fastlane/FastlanePlugin.groovy
src/main/groovy/wooga/gradle/fastlane/FastlanePluginConsts.groovy
src/main/groovy/wooga/gradle/fastlane/FastlanePluginExtension.groovy
src/main/groovy/wooga/gradle/fastlane/internal/DefaultFastlanePluginExtension.groovy
src/main/groovy/wooga/gradle/fastlane/internal/PropertyLookup.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/PilotUpload.groovy
src/main/resources/META-INF/gradle-plugins/net.wooga.fastlane.properties
src/test/groovy/wooga/gradle/fastlane/FastlanePluginSpec.groovy
src/test/groovy/wooga/gradle/fastlane/XcodeBuildPluginActivationSpec.groovy

This patch adds a simple plugin definiton for `fastlane`. This allows to setup shared configuration in a single extention. I implemented only two settings in the provided fastlane extension: `username` and `password`.
| property              | gradle property name              | environment variable                |
| --------------------- | --------------------------------- | ----------------------------------- |
| username              | `fastlane.username`               | `FASTLANE_USERNAME`                 |
| password              | `fastlane.password`               | `FASTLANE_PASSWORD`                 |
In this case, we use the same env names as fastlanes would use as well.
Changes
=======
* ![ADD] ![GRADLE] `FastlanePlugin` with defaults …

Add fastlane gradle plugin

---

lib/macos-security/src/main/groovy/com/wooga/security/Domain.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/DefaultKeychain.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/ListKeychains.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/LoginKeychain.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/MultiKeychainCommand.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/DefaultKeychainSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/ListKeychainsSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/LoginKeychainSpec.groovy

Add new keychain command implementations for:
* list-keychains
* default-keychain
* login-keychain
* ![ADD] `ListKeychains` security command
* ![ADD] `DefaultKeychain` security command
* ![ADD] `LoginKeychain` security command …

Add additional keychain commands

---

lib/macos-security/src/main/groovy/com/wooga/security/Domain.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/CreateKeychain.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/DefaultKeychain.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/ListKeychains.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/LoginKeychain.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/MultiKeychainCommand.groovy
lib/macos-security/src/main/groovy/com/wooga/security/command/SecurityCommand.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/AddGenericPasswordSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/AddInternetPasswordSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/AddPasswordSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/CreateKeychainSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/DefaultKeychainSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/FindGenericPasswordSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/FindInternetPasswordSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/FindPasswordSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/ImportSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/ListKeychainsSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/LoginKeychainSpec.groovy
lib/macos-security/src/test/groovy/com/wooga/security/command/ShowKeychainInfoSpec.groovy

This is a small fix. This patch makes sure the security command implemenations throw `NullPointerException`s instead of `IllegalArgumentExceptions` when provided parameters are null or contain null in case of list based options.
* ![IMPROVE] throw `NullPointerException` when provided parameter is null …

Throw NullPointerException if provided securtity command parameter is null

---

src/integrationTest/groovy/wooga/gradle/fastlane/FastlanePluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/AbstractFastlaneTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/PilotUploadIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/SighRenewIntegrationSpec.groovy
src/main/groovy/wooga/gradle/fastlane/FastlaneActionSpec.groovy
src/main/groovy/wooga/gradle/fastlane/FastlanePlugin.groovy
src/main/groovy/wooga/gradle/fastlane/FastlanePluginConsts.groovy
src/main/groovy/wooga/gradle/fastlane/FastlanePluginExtension.groovy
src/main/groovy/wooga/gradle/fastlane/internal/DefaultFastlanePluginExtension.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/AbstractFastlaneTask.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/PilotUpload.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/SighRenew.groovy

This patch adds missing setup to use the an appstore connection key with fastlane. Fastlane commands expect a json file with all information passed to with `--api-key-path` commandline argument. More informations about this file can be found [here](https://docs.fastlane.tools/app-store-connect-api/#using-fastlane-api-key-json-file)
This patch adds all gradle properties to pass down this field. The path to the file can also be configured in the fastlane plugin extension, gradle properties or environment variables.
| property              | gradle property name              | environment variable                |
| --------------------- | --------------------------------- | ----------------------------------- |
| apiKeyPath            | `fastlane.apiKeyPath`             | …

Implement appstore connection auth for fastlane

---

build.gradle
lib/spock-macos-keychain-extension/build.gradle
settings.gradle

This patch moves the helper library `macos-keychain` to a new repository https://github.com/wooga/macos-security.groovy Its not available through jcenter just now so to use it we need to configure a repository to fetch it from:
```groovy
repositories {
maven {
url  "https://dl.bintray.com/wooga/maven"
}
}
```
I send a request to jcenter to host this library. But that might take a few minutes/hours.
For use in a gradle project souround this with a `buildScript` block.
* ![IMPROVE] move library `macos-security` to external repo
[CHANGE]:http://resources.atlas.wooga.com/icons/icon_change.svg …

Move library macos-security to external repo

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/ImportCodeSigningIdentityIntegrationSpec.groovy
src/main/groovy/com/wooga/security/FindIdentityResult.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ImportCodeSigningIdentity.groovy
src/test/groovy/com/wooga/security/SecurityHelper.groovy

This patch adds a new ios specific task type to the `net.wooga.build-unity-ios` plugin. It's main purpose is to import code signing identities (private key + certificate) to a configured keychain.
The task implementation supports validation to check if the provided p12 file actually contained a valid identity with the given name. One can configure to allow invalid signing identities.
* ![ADD] `ImportCodeSigningIdentity` task …

Add new task type ImportCodeSigningIdentity

---

Jenkinsfile
build.gradle
src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/UnityIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/TestUnityAsset.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/UnityBuildPluginSecretHandlingIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/GradleBuildIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTaskIntegrationSpec.groovy

With a recent change in the plugin `net.wooga.unity`, the plugin has a stricter parsing defintion for unity asset objects. This means that we can't simply create a yaml file and let it parse.
The patch adds the normal asset file header for Unity assets so that the implementation works as expected.
* ![FIX] generate valid appconfig in tests …

Fix generate valid app configs in tests

---

src/integrationTest/groovy/net/wooga/system/ProcessList.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/ListKeychainTask.groovy
src/main/groovy/wooga/gradle/fastlane/internal/PropertyLookup.groovy

This patch adds a shutdown handler to the `net.wooga.build-io` plugin to cleanup created build keychains in case of abrupt build process termination. It uses the `java.lang.Runtime#addShutdownHook` API and registeres a hook after the `addKeychain` task was executed and removes said hook when `removeKeychian` was executed. These shutdown hooks run even during normal termination so it is crucial to only do the work when needed.
I setup a tests that runs a build with a very long task execution in a forked jvm. The test framework will spawn a new gradle deamon which we will pin to a different gradle version to find in the process list of macOS. The tests will run with multiple kill signals to verify the shutdown hook execution.
This whole logic only works for normal kill signals like `TERM` …

Improve keychain cleanup after gradle process kill

---

build.gradle

With the move to gradle 6 we also had to adjust the dependency components. The `compile` component is no longer available and one needs to use the `implementation` in most cases. I moved some dependencies to the `api` component so they can be directly used by the user of this plugin.
* ![IMPROVE] exported API …

Improve exported APIs

---

Jenkinsfile
build.gradle
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/ExportArchiveIntegrationSpec.groovy

atlas plugin gradle plugin updated to 2.2.0, and added Sonarqube support on Jenkinsfile.
* ![UPDATE] `atlas-plugin` gradle plugin to `2.2.0`
* ![NEW] Sonarqube project being uploaded on Jenkinsfile execution
[NEW]:https://resources.atlas.wooga.com/icons/icon_new.svg "New" …

Updated atlas plugin to 2.2.0

---

build.gradle
src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/SonarQubeConfiguration.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginConventions.groovy
src/main/groovy/wooga/gradle/fastlane/FastlanePluginConventions.groovy
src/main/groovy/wooga/gradle/xcodebuild/XcodeBuildPluginConventions.groovy
src/main/resources/atlas-build-unity.project-fixes.props
src/test/groovy/wooga/gradle/build/unity/UnityBuildPluginSpec.groovy

Added new unity-opinionated `sonarqube` task, associated `sonarBuildUnity` task and integration with the `atlas-dotnet-sonarqube` plugin. Updated `atlas-unity` as well, it's latest version is needed to run sonarqube. More details on how to use the task in the `atlas-dotnet-sonarqube` project README file.
* ![ADD] This plugin now applies the `atlas-dotnet-sonarqube` plugin.
* ![ADD] sonarqube integration using the `atlas-dotnet-sonarqube` plugin.
* ![CHANGE] unity test code coverage enabled by default …

Add Sonarqube task

---

src/main/groovy/wooga/gradle/build/unity/SonarQubeConfiguration.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/test/groovy/wooga/gradle/build/unity/UnityBuildPluginSpec.groovy

Unity project Assets/Tests folder added to default sonarqube coverage (`sonar.coverage.exclusions`) and cpd(`sonar.cpd.exclusions`) exclusions. 
* ![ADD] Assets/Tests folder added to default sonarqube coverage and cdp exclusions.  …

Added unity tests folder to default sonarqube exclusions

---

src/integrationTest/groovy/wooga/gradle/build/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/KeychainSearchListSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/SecurityResetKeychainSearchListIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/SecuritySetKeychainSearchListIntegrationSpec.groovy
src/main/groovy/wooga/gradle/macOS/security/tasks/AbstractSecurityKeychainSearchListTask.groovy
src/main/groovy/wooga/gradle/macOS/security/tasks/SecurityResetKeychainSearchList.groovy
src/main/groovy/wooga/gradle/macOS/security/tasks/SecuritySetKeychainSearchList.groovy

This is a more generic implementation of the old `ListKeychain` task. It uses the `MacOsKeychainSearchList` class to add/remove keychains to the search list. I also split out the `reset` action into it's own command `SecurityResetKeychainSearchList` as the interface is different.
* ![ADD] `SecuritySetKeychainSearchList` task
* ![ADD] `SecurityResetKeychainSearchList` task …

Add keychain search list manipulation tasks

---

build.gradle

This is an update to the latest fix version of `net.wooga.plugins`. The patch will address incompatibility issues with jdk8 due to a version bump of jgit.
* ![UPDATE] `net.wooga.plugins` to version `2.2.3` …

Update net.wooga.plugins to version 2.2.3

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/KeychainTaskSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/ios/internal/DefaultIOSBuildPluginExtension.groovy
src/test/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginSpec.groovy

The plugin extension for `net.wooga.build-unity-ios` was not setup to use `Property`/`Provider` APIs. I changed this and moved the interface into a trait object. I had to implement some brealing changes to make the interface clearer
* ![IMPROVE] build-unity-ios plugin extension …

Improve build unity ios plugin extension [ATLAS-437]

---

src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/XcodeArchiveIntegrationSpec.groovy
src/main/groovy/wooga/gradle/xcodebuild/config/BuildSettings.groovy
src/main/groovy/wooga/gradle/xcodebuild/tasks/XcodeArchive.groovy

Small fix for an issue which made no real harm at runtime at the moment but needs a fix in any case. The `Provider` for build arguments in `XcodeArchive` is mutating the `Buildsettings` object of the task while constructing the argument `List`. The provider itself gets called multiple times and manipulates the BuildSettings again and again and again. I decided to go with the `clone` approuch here instead of memorizing the whole closure. First I'm not always sure if the first invocation is already late enough so that all fields are set correctly.
While testing this I saw that my initial `clone` implementation in `BuildSettings` had a major bug. I also need to clone the underlying `HashMap` which holds all passed values. This fix allows to call `buildArguments.get()` multiple times without …

Fix adding buildkeychain flag multiple times to OTHER_CODE_SIGN_FLAGS [ATLAS-468]

---

Jenkinsfile
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/AbstractXcodeTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/ExportArchiveIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/xcodebuild/tasks/XcodeArchiveIntegrationSpec.groovy
src/main/groovy/wooga/gradle/xcodebuild/internal/XcodeBuildAction.groovy

The old tests had to force a testrun with xcode 12 setup. XCode 13 changed it's output and the tests won't be able to cover over multiple versions. I decided to make the test case simpler by only testing a single line of the output for the formatting instead of trying to match the whole output with regex. I also needed to adjust the output handling from xcodebuild because error lines are not printed to stderr instead of stdout as before with Xcode12. I simply merge both streams together for a single log file.
* ![IMPROVE] simplify xcode format check to be version agnostic
* ![FIX] XCode13 error output handling …

Remove the need for special xcode version during tests [ATLAS-498]

---

src/integrationTest/groovy/wooga/gradle/build/unity/tasks/GradleBuildIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/GradleBuild.groovy

This patch adds a new input property `continueOnFailure` which will set a the matching property on the `GradleBuild` launcher. If this property is not set, the task will check the start parameter of the running gradle instance if it has the flag set which means it will by default pass the flag through analog to the loglevel.
If the `--continue` flag is already set in the tasks buildarguments it will be used instead.
* ![IMPROVE] `GraddleBuild` continueOnFailure flag/passthrough …

Implement continueOnFailure passthrough/property for GradleBuild task

---

src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy

The dependecy declaration got removed in one of the last patches. This yields issues when the host system doesn't privide the provisioning profiles to sign.
* ![FIX] missing dependency to `importProvisioningProfiles` task for xcodeArchive …

Fix missing dependency to importProvisioningProfiles for xcodeArchive [ATLAS-580]

---

build.gradle
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/FetchSecretsTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/tasks/SecretSpecIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/FetchSecrets.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/GradleBuild.groovy
src/main/groovy/wooga/gradle/build/unity/tasks/UnityBuildPlayerTask.groovy
src/test/groovy/wooga/gradle/secrets/internal/EncryptionSpecHelper.groovy

This patch add the removed task type `FetchSecrets` to this plugin. In the future this tasks won't be needed anymore. This move is just for backwards compatibility to be able to use the secrets plugin directly in other projects.
* ![ADD] removed `FetchSecrets` task from `net.wooga.secrets` …

Add FetchSecret task from net.wooga.security

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/CocoaPodSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/PodInstallTaskSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/PodInstallTask.groovy
src/test/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginSpec.groovy

This patch changes drastically how the xcode related tasks are created, named and managed. The old implementation scanned the whole project directory tree for `.xcodeproj` directories. The idea was to be able to manage multiple projects with one plugin. I changed how this works to simplify the setup. In our opinioted view only a single xcode project is located in the project directory. We set a default value to `Unity-iPhone` as the base name forthis project. This and the xcode project directory property can be set in the extension. We now only setup tasks for this one project. This makes the base setup way simpler.
I'm still not happy how to handle xcodeproj and xcworkspace directories. I deciced to go the `xcodeProjectPath` + `xcodeProjectBaseName` + `extension` route. The downside is …

Improve net.wooga.build-unity-ios xcode task setup

---

src/integrationTest/groovy/wooga/gradle/build/UnityBuildPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginConventions.groovy
src/main/groovy/wooga/gradle/build/unity/UnityBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/internal/DefaultUnityBuildPluginExtension.groovy

The `net.wooga.build-unity` plugin defined dependencies to the basic lifecycle tasks `assemble, build, check, publish) when the `defaultAppConfigName` property was provided. The only missing key is the `export` method.
This patch adds the missing link and allows to call `export` on a project with `defaultAppConfigName` set to easily run and execute the correct `export` variant.
I also added a way of skipping the export action. This might become usefull/needed for teams who need to enforce that the export will be skipped. At the moment this has to be done since most Unity projects still alter the source files when building.
* ![ADD] lifecycle task `export`
* ![ADD] `skipExport` logic for export task actions
[NEW]:      https://resources.atlas.wooga.com/icons/icon_new.svg "New"
[ADD]: …

Add export lifecycle task and skipExport logic

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/IOSBuildIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/xcodebuild/config/ExportOptions.groovy
src/test/groovy/wooga/gradle/xcodebuild/config/ExportOptionsSpec.groovy

This patch adds a new way to configure the export options plist file needed during the archive command run. A lot of information we need for a complete build is tracked multiple times. This patch tries to make it easier to define these config values only once. On the other hand it gives a new way of configuring the content of the exportOptions.plist file in the build.gradle file.
The first change is the introduction of a new provider in the ios plugin extension:
`Provider<ExportOptions> getExportOptions()`
With this provider one can read and use the values in the `exportOptions.plist` file at runtime without additional parsing.
With this provider created I set some conventions to point to the matching value in this new provider
```groovy …
```

Improve exportOptions.plist handling [ATLAS-599]

---

src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy

A simple patch to set some basic conventions for the default settings for the build keychain. Without these the keychain would be created with the default settings (lock after sleep and lock after 5 minutes) This will ensure that longer builds still can access the keychain after a compile.
I also set a domain value for the keychain operation to not write into the system values etc. This is just a precauthion since the user in question can only set user keychains anyway. But the commandline arguments can be smaller and it is in general a better way.
* ![IMPROVE] default build keychain settings
* ![IMPROVE] set domain value for keychain searchlist operations …

Improve build keychain default settings

---

build.gradle
src/integrationTest/groovy/wooga/gradle/fastlane/FastlanePluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/SighRenewBatchIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/SighRenewIntegrationSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/fastlane/FastlanePlugin.groovy
src/main/groovy/wooga/gradle/fastlane/FastlanePluginConventions.groovy
src/main/groovy/wooga/gradle/fastlane/models/FastLaneSpec.groovy
src/main/groovy/wooga/gradle/fastlane/models/SighRenewSpec.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/AbstractFastlaneTask.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/SighRenew.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/SighRenewBatch.groovy

This patch adds a new fastlane task type `SighRenewBatch` which allows to set a map of `bundleId` -> `profileName`.  This allows to set the map pulled from the `exportOption.plist` into the `importProvisioningProfiles` task.
I'm not 100% happy with the implementation but one could revisit this with another patch to rework the inner workings.
At the moment the new task type simply extends `SighRenew` and adds a `profiles` property which gets looped over. The task action of `SighRenew` is called multiple times. This has the desired effect but can cause issues with input caching etc. I'm fine with this from a first version prespective
* ![IMPROVE] multiple provisioning profiles support …

Improve multiple provisioning profiles support

---

src/integrationTest/groovy/wooga/gradle/macOS/security/SecurityIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/SecurityTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/InteractiveSecurityTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/KeychainSearchListSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/SecurityCreateKeychainIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/SecurityLockKeychainIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/SecurityResetKeychainSearchListIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/SecuritySetKeychainSearchListIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/macOS/security/tasks/SecurityUnlockKeychainIntegrationSpec.groovy

This patch updates the test setup for the `net.wooga.macos-security` plugin to the latest conventions from gradle commons.
* ![IMPROVE] `net.wooga.macos-security` test
[IOS]:http://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS" …

Improve test setup for net.wooga.macos-security test

---

src/integrationTest/groovy/wooga/gradle/fastlane/FastlaneIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/AbstractFastlaneTaskIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/fastlane/tasks/PilotUploadIntegrationSpec.groovy
src/main/groovy/wooga/gradle/fastlane/models/FastLaneTaskSpec.groovy
src/main/groovy/wooga/gradle/fastlane/models/PilotUploadSpec.groovy
src/main/groovy/wooga/gradle/fastlane/models/SighRenewSpec.groovy
src/main/groovy/wooga/gradle/fastlane/tasks/SighRenewBatch.groovy

I was under the assumption what when one overrides a gradle task type which contains an `TaskAction` annotated method that if one annotates another new method that the original action is no longer executed. That is not the case. So I fixed this here to override the `exec` method rather than declaring another action to be executed.
* ![FIX] overload for task action in `SighRenewBatch` task
[UPDATE]:http://resources.atlas.wooga.com/icons/icon_update.svg …

Fix overload for task action for SighRenewBatch

---

src/integrationTest/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/build/unity/ios/tasks/CocoaPodSpec.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPlugin.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginConventions.groovy
src/main/groovy/wooga/gradle/build/unity/ios/IOSBuildPluginExtension.groovy
src/main/groovy/wooga/gradle/build/unity/ios/tasks/PodInstallTask.groovy

This patch includes three kind of related changes.
1. use new `ExecSpec` for `PodInstall` task
2. bind cocoapods executable name / path to extension
3. bind extension properties to conventions (env, property)
The cocoapods task used a utility class to find the nearest `pod` executable in the `PATH`. This system works but is not future proof. We are in the works to provide a way to lazy install the tool during a build and need an internal property to set the executable name / path. We developed the `ExecSpec` class which we also already used in the `net.wooga.fastlane` plugin for the same reason.
To make this new value easily setable, also in case we create more cocoapod task types, I added a new nested object inside the `IOSBuildPluginExtension` called 'cocoapods` which interally is also …

Improve property mapping for net.wooga.build-unity-ios
